"""empty message

Revision ID: e66884bb260f
Revises: c23d2a740fc7
Create Date: 2016-11-28 22:19:19.418769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e66884bb260f'
down_revision = 'c23d2a740fc7'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tv_serie', sa.Column('year', sa.Date(), nullable=True))
    op.create_unique_constraint(None, 'tv_serie', ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, 'tv_serie', type_='unique')
    op.drop_column('tv_serie', 'year')
    ### end Alembic commands ###
